version: '3'
services:
  web:
    image: sources
    build: "yarn build"
    ports:
    - "5000:5000"
    depends_on:
    - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
